name: Build

on: [push, pull_request]

jobs:
  container-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
      - name: env
        run: |
          cat /proc/cpuinfo
          free -m
      - name: checkout - project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        run: |
          make nro -j4
      - name: store
        uses: actions/upload-artifact@v2
        with:
          name: ftpd.nro
          path: ftpd.nro
